import type { LocalizedValue } from "@tayyar/utils";

const text = (ar: string, en: string): LocalizedValue => ({ ar, en });

export const heroAppCopy = {
  common: {
    heroBrand: text("طيّار Hero", "Tayyar Hero"),
    signOut: text("خروج", "Sign out"),
    back: text("رجوع", "Back"),
    refresh: text("تحديث", "Refresh"),
    restoringSession: text("جارٍ تجهيز الجلسة...", "Restoring session..."),
    offline: text("غير متصل", "Offline"),
    connected: text("متصل", "Connected"),
    noData: text("لا توجد بيانات", "No data"),
    noAddress: text("لا يوجد عنوان", "No address"),
    unexpectedError: text("حدث خطأ غير متوقع.", "An unexpected error occurred."),
    syncNow: text("مزامنة الآن", "Sync now"),
    queuedForSync: text("تم حفظ الإجراء للمزامنة.", "The action was saved for sync."),
    pendingSync: text("إجراءات بانتظار المزامنة", "Actions waiting to sync"),
    syncedNow: text("تمت المزامنة.", "Sync completed."),
  },
  login: {
    title: text("دخول الطيارين", "Hero sign in"),
    subtitle: text("دخول الطيارين لتنفيذ المهام ومتابعة المستحقات.", "Sign in to manage missions and earnings."),
    gateway: text("بوابة التشغيل", "Access"),
    startWithPhone: text("ابدأ برقم الموبايل", "Start with mobile number"),
    enterOtp: text("أدخل رمز التحقق", "Enter verification code"),
    phoneBody: text("أدخل رقم الطيار للمتابعة.", "Enter the hero phone number to continue."),
    otpBody: text("استخدم رمز الاختبار 1234 في بيئة التطوير الحالية.", "Use test code 1234 in the current development environment."),
    phoneLabel: text("رقم الموبايل", "Mobile number"),
    phoneSafety: text("الدخول متاح للطيارين المصرح لهم فقط.", "Access is limited to authorized heroes."),
    otpLabel: text("رمز التحقق", "Verification code"),
    editPhone: text("تعديل رقم الموبايل", "Edit mobile number"),
    sendCode: text("إرسال الرمز", "Send code"),
    openBoard: text("دخول لوحة العمل", "Open work board"),
  },
  dashboard: {
    title: text("لوحة العمل", "Work board"),
    subtitle: text("المهام والحالة والمستحقات.", "Tasks, status, and earnings."),
    workState: text("حالة العمل", "Work status"),
    readyQuestion: text("جاهز للعمل؟", "Ready to go online?"),
    onlineNow: text("أنت متصل حالياً.", "You are online now."),
    offlineBody: text("فعّل الجاهزية لاستقبال المهام.", "Go online to receive missions."),
    onlineBody: text("حالتك وموقعك محدثان للمشرف.", "Your status and location are live for supervisors."),
    turnOn: text("تشغيل الجاهزية", "Go online"),
    turnOff: text("إيقاف الجاهزية", "Go offline"),
    activeMissions: text("المهام الحالية", "Active missions"),
    completedToday: text("طلبات مكتملة", "Completed today"),
    todayIncome: text("دخل اليوم", "Today's earnings"),
    totalEarnings: text("إجمالي الدخل", "Total earnings"),
    payoutDue: text("مستحقات السحب", "Pending payout"),
    quickView: text("ملخص سريع", "Quick summary"),
    todayMetrics: text("مؤشرات اليوم", "Today's metrics"),
    missionFlow: text("المهام", "Missions"),
    currentMissions: text("المهام الحالية", "Current missions"),
    missionsSubtitle: text("كل مهمة بحالتها الحالية.", "Each mission with its current status."),
    openMission: text("فتح المهمة", "Open mission"),
    lastSync: text("آخر مزامنة", "Last sync"),
    locationPermissionTitle: text("صلاحية الموقع مطلوبة", "Location access is required"),
    locationPermissionBody: text("فعّل صلاحية الموقع قبل تشغيل الجاهزية.", "Enable location permission before going online."),
    statusUpdated: text("تم تحديث الحالة.", "Status updated."),
    noMissionsOffline: text("فعّل الجاهزية لتظهر المهام هنا.", "Go online to receive missions here."),
    noMissionsOnline: text("لا توجد مهام حالياً.", "No active missions right now."),
    pendingSyncBody: text("لديك إجراءات محفوظة ستتحدث عند رجوع الاتصال.", "You have saved actions that will sync when the connection returns."),
  },
  wallet: {
    title: text("المحفظة", "Wallet"),
    subtitle: text("الرصيد والحركات وطلبات السحب.", "Balance, transactions, and payout requests."),
    availableBalance: text("الرصيد المتاح الآن", "Available balance"),
    withdrawNote: text("طلبات السحب تراجع مالياً قبل التنفيذ.", "Payout requests are reviewed by finance before processing."),
    fullCashout: text("طلب سحب كامل الرصيد", "Withdraw full balance"),
    totalIncome: text("إجمالي المقبوض", "Total received"),
    totalDeductions: text("إجمالي الخصومات", "Total deductions"),
    ledger: text("السجل المالي", "Ledger"),
    latestMoves: text("آخر الحركات", "Latest activity"),
    latestMovesSubtitle: text("كل حركة مرتبطة بمحفظتك تظهر هنا.", "Every wallet transaction appears here."),
    filterAll: text("الكل", "All"),
    filterIn: text("دخول", "Money in"),
    filterOut: text("خصم", "Money out"),
    filterPayout: text("سحب", "Payouts"),
    emptyTitle: text("لا توجد حركات بعد", "No transactions yet"),
    emptyBody: text("ستظهر الحركات هنا تلقائياً.", "Transactions will appear here automatically."),
    filteredEmptyTitle: text("لا توجد نتائج لهذا الفلتر", "No transactions for this filter"),
    filteredEmptyBody: text("غيّر الفلتر أو حدّث الصفحة لعرض حركات أخرى.", "Change the filter or refresh to view other transactions."),
    noBalanceTitle: text("لا يوجد رصيد", "No balance"),
    noBalanceBody: text("الرصيد الحالي صفر، لا يمكن إنشاء طلب سحب.", "The current balance is zero, so a payout request cannot be created."),
    createdTitle: text("تم إنشاء الطلب", "Request created"),
    createdBody: text("تم إرسال طلب السحب للمراجعة المالية.", "The payout request was sent to finance for review."),
    completed: text("مكتمل", "Completed"),
    recorded: text("مسجل", "Recorded"),
  },
  order: {
    unavailable: text("المهمة غير متاحة حالياً أو انتهت.", "This mission is not available right now or has already ended."),
    loading: text("جارٍ تجهيز تفاصيل المهمة...", "Loading mission details..."),
    currentMission: text("المهمة الحالية", "Current mission"),
    pickupFirst: text("اتجه إلى نقطة الاستلام.", "Head to the pickup point."),
    enroute: text("أنت في الطريق إلى العميل.", "You are on the way to the customer."),
    handoff: text("راجع رمز التسليم قبل الإغلاق.", "Verify the delivery code before closing the mission."),
    completed: text("تم إنهاء المهمة.", "Mission completed."),
    route: text("المسار", "Route"),
    routeTitle: text("تفاصيل المسار", "Route details"),
    routeSubtitle: text("الاستلام والتسليم والتواصل السريع.", "Pickup, drop-off, and quick contact."),
    pickup: text("الاستلام", "Pickup"),
    dropoff: text("التسليم", "Drop-off"),
    branch: text("الفرع", "Branch"),
    unavailableAddress: text("العنوان غير متاح.", "Address unavailable."),
    callBranch: text("اتصال بالفرع", "Call branch"),
    callCustomer: text("اتصال بالعميل", "Call customer"),
    openMaps: text("فتح الملاحة", "Open navigation"),
    otpTitle: text("اكتب رمز التسليم", "Enter delivery code"),
    otpBody: text("اطلب من العميل رمز التسليم ثم أدخله هنا.", "Ask the customer for the delivery code, then enter it here."),
    confirmPickup: text("تأكيد الاستلام", "Confirm pickup"),
    arrivedCustomer: text("وصلت للعميل", "Mark as arrived"),
    confirmDelivery: text("تأكيد التسليم", "Confirm delivery"),
    pickupStage: text("مرحلة الاستلام", "Pickup stage"),
    enrouteStage: text("في الطريق", "On the way"),
    handoffStage: text("تسليم آمن", "Secure handoff"),
    doneStage: text("تمت", "Done"),
    reviewStage: text("مراجعة", "Review"),
    otpRequired: text("اكتب رمز تسليم من 4 أرقام.", "Enter a 4-digit delivery code."),
    noPhoneTitle: text("الرقم غير متاح", "Phone unavailable"),
    noPhoneBody: text("لا يوجد رقم مسجل لهذا الفرع حالياً.", "No phone number is recorded for this branch right now."),
    callError: text("تعذر فتح الاتصال.", "Could not open the phone app."),
    mapsError: text("تعذر فتح الملاحة.", "Could not open navigation."),
    offlineQueuedBody: text("تم حفظ الخطوة للمزامنة عند رجوع الاتصال.", "The step was saved to sync when the connection returns."),
    verifyNeedsConnection: text("تأكيد التسليم يحتاج اتصالاً مباشراً.", "Delivery confirmation requires a live connection."),
  },
};
