import type { LocalizedValue } from "@tayyar/utils";

const text = (ar: string, en: string): LocalizedValue => ({ ar, en });

export const heroAppCopy = {
  common: {
    heroBrand: text("طيار هيرو", "Tayyar Hero"),
    loading: text("جارٍ التحميل...", "Loading..."),
    refresh: text("تحديث", "Refresh"),
    retry: text("إعادة المحاولة", "Retry"),
    signOut: text("تسجيل الخروج", "Sign out"),
    back: text("رجوع", "Back"),
    save: text("حفظ", "Save"),
    close: text("إغلاق", "Close"),
    noData: text("لا توجد بيانات حالياً", "No data right now"),
    unexpectedError: text("حدث خطأ غير متوقع. حاول مرة أخرى.", "Something went wrong. Please try again."),
    restoringSession: text("جارٍ تجهيز جلستك...", "Restoring your session..."),
    offline: text("غير متصل", "Offline"),
    connected: text("متصل", "Connected"),
    pendingSync: text("بانتظار المزامنة", "Waiting to sync"),
    queuedForSync: text("تم حفظ الإجراء وسيتم إرساله عند عودة الاتصال.", "Action saved and will sync when connection returns."),
    syncedNow: text("تمت المزامنة بنجاح.", "Sync completed successfully."),
  },
  auth: {
    title: text("تسجيل دخول الطيار", "Hero sign in"),
    subtitle: text("دخول سريع وآمن للوصول إلى المهام والحالة والمحفظة.", "Fast and secure sign in for missions, status, and wallet."),
    phoneTitle: text("ابدأ برقم الهاتف", "Start with your phone"),
    phoneBody: text("أدخل رقم الهاتف المسجل على حسابك.", "Enter the phone number linked to your account."),
    phoneLabel: text("رقم الهاتف", "Phone number"),
    sendCode: text("إرسال الرمز", "Send code"),
    sendingCode: text("جارٍ إرسال الرمز...", "Sending code..."),
    codeSent: text("تم إرسال رمز التحقق.", "Verification code sent."),
    otpTitle: text("أدخل رمز التحقق", "Enter verification code"),
    otpBody: text("أدخل الرمز المكوّن من 4 أرقام لإكمال الدخول.", "Enter the 4-digit code to continue."),
    otpLabel: text("رمز التحقق", "Verification code"),
    verifyCode: text("دخول", "Sign in"),
    verifyingCode: text("جارٍ التحقق...", "Verifying..."),
    resendCode: text("إعادة إرسال الرمز", "Resend code"),
    editPhone: text("تعديل الرقم", "Change number"),
    accountMissing: text("لا يوجد حساب نشط لهذا الرقم.", "No active account found for this phone number."),
    wrongCode: text("الرمز غير صحيح أو منتهي الصلاحية.", "The code is invalid or expired."),
    trustedDevice: text("سيبقى هذا الجهاز موثوقاً للدخول السريع لاحقاً.", "This device will stay trusted for faster sign in later."),
    qaHint: text("رقم الاختبار: 1000000004", "QA phone: 1000000004"),
    qaCodeHint: text("رمز الاختبار: 1234", "QA code: 1234"),
  },
  home: {
    title: text("لوحة العمل", "Work board"),
    subtitle: text("كل ما تحتاجه الآن في مكان واحد.", "Everything you need right now in one place."),
    ready: text("جاهز للعمل", "Ready for work"),
    readyBody: text("فعّل الجاهزية ليبدأ توزيع المهام عليك.", "Go online to start receiving missions."),
    offlineBody: text("أنت غير متصل حالياً ولن تصلك مهام جديدة.", "You are offline and will not receive new missions."),
    onlineBody: text("حالتك وموقعك ظاهران لفريق التشغيل.", "Your status and location are visible to operations."),
    goOnline: text("تشغيل الجاهزية", "Go online"),
    goOffline: text("إيقاف الجاهزية", "Go offline"),
    currentMission: text("المهمة الحالية", "Current mission"),
    openMission: text("فتح المهمة", "Open mission"),
    noMissionTitle: text("لا توجد مهمة نشطة", "No active mission"),
    noMissionBody: text("عند وصول مهمة جديدة ستظهر هنا مباشرة.", "When a new mission arrives, it will appear here."),
    deliveriesToday: text("طلبات اليوم", "Deliveries today"),
    pendingPayout: text("مستحق قيد الصرف", "Pending payout"),
    totalEarnings: text("إجمالي الأرباح", "Total earnings"),
    syncState: text("آخر مزامنة", "Last sync"),
    attention: text("تحتاج انتباهك", "Needs your attention"),
    permissionRequired: text("فعّل إذن الموقع قبل تشغيل الجاهزية.", "Enable location permission before going online."),
  },
  missions: {
    title: text("المهام", "Missions"),
    subtitle: text("المهام الجارية والجاهزة للتنفيذ الآن.", "Current missions ready for action."),
    emptyTitle: text("لا توجد مهام حالياً", "No missions right now"),
    emptyBody: text("حافظ على الجاهزية وستظهر المهمة القادمة هنا.", "Stay online and the next mission will appear here."),
    pickup: text("استلام", "Pickup"),
    enroute: text("في الطريق", "En route"),
    arrived: text("عند العميل", "Arrived"),
    delivered: text("تم التسليم", "Delivered"),
    branch: text("الفرع", "Branch"),
    customer: text("العميل", "Customer"),
    address: text("العنوان", "Address"),
    open: text("فتح", "Open"),
  },
  order: {
    currentMission: text("المهمة الحالية", "Current mission"),
    loading: text("جارٍ تحميل المهمة...", "Loading mission..."),
    unavailable: text("هذه المهمة غير متاحة حالياً.", "This mission is not available right now."),
    route: text("المسار", "Route"),
    routeTitle: text("خطة المهمة", "Mission route"),
    routeSubtitle: text("الاستلام والتسليم والاتصال السريع في شاشة واحدة.", "Pickup, drop-off, and quick contact in one place."),
    pickup: text("الاستلام", "Pickup"),
    dropoff: text("التسليم", "Drop-off"),
    branch: text("الفرع", "Branch"),
    unavailableAddress: text("لا يوجد عنوان واضح حالياً.", "No clear address is available right now."),
    pickupFirst: text("ابدأ من نقطة الاستلام أولاً.", "Start from the pickup point."),
    enroute: text("أنت الآن في الطريق إلى العميل.", "You are now on the way to the customer."),
    handoff: text("تأكد من رمز التسليم قبل الإنهاء.", "Confirm the delivery code before finishing."),
    completed: text("تم إنهاء المهمة بنجاح.", "Mission completed successfully."),
    confirmPickup: text("تأكيد الاستلام", "Confirm pickup"),
    arrivedCustomer: text("تم الوصول للعميل", "Mark arrived"),
    confirmDelivery: text("تأكيد التسليم", "Confirm delivery"),
    callBranch: text("اتصال بالفرع", "Call branch"),
    callCustomer: text("اتصال بالعميل", "Call customer"),
    openMaps: text("فتح الملاحة", "Open navigation"),
    noPhoneTitle: text("لا يوجد رقم متاح", "No phone available"),
    noPhoneBody: text("لا يوجد رقم اتصال لهذه الجهة حالياً.", "There is no phone number available right now."),
    callError: text("تعذر فتح تطبيق الاتصال.", "Could not open the phone app."),
    mapsError: text("تعذر فتح تطبيق الملاحة.", "Could not open the navigation app."),
    otpTitle: text("رمز التسليم", "Delivery code"),
    otpBody: text("أدخل رمز التسليم من العميل قبل الإنهاء.", "Enter the customer delivery code before finishing."),
    otpRequired: text("أدخل رمز التسليم المكوّن من 4 أرقام.", "Enter the 4-digit delivery code."),
    verifyNeedsConnection: text("تأكيد التسليم يحتاج اتصالاً مباشراً بالإنترنت.", "Delivery confirmation requires a live internet connection."),
    offlineQueuedBody: text("تم حفظ آخر إجراء وسيرسل تلقائياً عند عودة الاتصال.", "The last action was saved and will sync automatically when connection returns."),
    pickupStage: text("استلام", "Pickup"),
    enrouteStage: text("في الطريق", "En route"),
    handoffStage: text("التسليم", "Handoff"),
    doneStage: text("مكتملة", "Done"),
    reviewStage: text("مراجعة", "Review"),
  },
  wallet: {
    title: text("المحفظة", "Wallet"),
    subtitle: text("الرصيد والعمولات والدفعات الأخيرة.", "Balance, commissions, and recent payouts."),
    availableBalance: text("الرصيد المتاح", "Available balance"),
    withdrawNote: text("سيتم إرسال طلب الصرف إلى الإدارة المالية للمراجعة.", "Your payout request will be sent to finance for review."),
    fullCashout: text("طلب صرف كامل الرصيد", "Request full payout"),
    totalIncome: text("إجمالي المقبوض", "Total received"),
    totalDeductions: text("إجمالي الخصومات", "Total deductions"),
    ledger: text("السجل المالي", "Ledger"),
    latestMoves: text("آخر الحركات", "Latest transactions"),
    latestMovesSubtitle: text("كل حركة مالية مرتبطة بمحفظتك تظهر هنا.", "Every wallet movement appears here."),
    filterAll: text("الكل", "All"),
    filterIn: text("إيداعات", "Money in"),
    filterOut: text("خصومات", "Money out"),
    filterPayout: text("سحب", "Payouts"),
    noBalanceTitle: text("لا يوجد رصيد متاح", "No available balance"),
    noBalanceBody: text("لا يوجد رصيد يمكن طلب صرفه حالياً.", "There is no balance available for payout right now."),
    createdTitle: text("تم إنشاء الطلب", "Request created"),
    createdBody: text("تم إرسال طلب الصرف للمراجعة.", "The payout request was sent for review."),
    completed: text("مكتملة", "Completed"),
    recorded: text("مسجلة", "Recorded"),
    filteredEmptyTitle: text("لا توجد نتائج لهذا الفلتر", "No transactions match this filter"),
    filteredEmptyBody: text("غيّر الفلتر لرؤية حركات أخرى.", "Change the filter to see other transactions."),
    emptyTitle: text("لا توجد حركات بعد", "No transactions yet"),
    emptyBody: text("ستظهر الحركات هنا بمجرد تسجيلها.", "Transactions will appear here as soon as they are recorded."),
  },
  profile: {
    title: text("الحساب", "Profile"),
    subtitle: text("اللغة والجلسة والإجازات وحالة الجهاز.", "Language, session, vacation, and device status."),
    vacation: text("الإجازات", "Vacation"),
    vacationBalance: text("الرصيد المتبقي", "Remaining balance"),
    requestVacation: text("طلب إجازة", "Request vacation"),
    requestType: text("نوع الإجازة", "Vacation type"),
    startDate: text("من تاريخ", "Start date"),
    endDate: text("إلى تاريخ", "End date"),
    reason: text("السبب", "Reason"),
    sendRequest: text("إرسال الطلب", "Submit request"),
    requestSent: text("تم إرسال طلب الإجازة.", "Vacation request submitted."),
    activeRequest: text("الطلب الحالي", "Current request"),
    history: text("سجل الطلبات", "Request history"),
    language: text("اللغة", "Language"),
    permissions: text("الأذونات", "Permissions"),
    locationPermission: text("إذن الموقع", "Location permission"),
    session: text("الجلسة", "Session"),
    trustedDevice: text("هذا الجهاز موثوق للدخول السريع.", "This device is trusted for faster sign in."),
    permissionsGranted: text("مفعّل", "Granted"),
    permissionsMissing: text("غير مفعّل", "Not granted"),
    annual: text("سنوية", "Annual"),
    sick: text("مرضية", "Sick"),
    emergency: text("طارئة", "Emergency"),
    unpaid: text("غير مدفوعة", "Unpaid"),
    pending: text("قيد المراجعة", "Pending"),
    approved: text("تمت الموافقة", "Approved"),
    rejected: text("مرفوضة", "Rejected"),
    cancelled: text("ملغية", "Cancelled"),
  },
} as const;
