import type { LocalizedValue } from "@tayyar/utils";

const text = (ar: string, en: string): LocalizedValue => ({ ar, en });

export const heroAppCopy = {
  common: {
    heroBrand: text("طيّار هيرو", "Tayyar Hero"),
    signOut: text("تسجيل الخروج", "Sign out"),
    back: text("رجوع", "Back"),
    refresh: text("تحديث", "Refresh"),
    restoringSession: text("جارٍ تجهيز الجلسة...", "Restoring your session..."),
    offline: text("غير متصل", "Offline"),
    connected: text("متصل", "Connected"),
    noData: text("لا توجد بيانات حالياً", "No data available right now"),
    noAddress: text("العنوان غير متاح", "Address unavailable"),
    unexpectedError: text("حدث خطأ غير متوقع. حاول مرة أخرى.", "Something went wrong. Please try again."),
    syncNow: text("مزامنة الآن", "Sync now"),
    queuedForSync: text(
      "تم حفظ الإجراء وسيُرسل عند عودة الاتصال.",
      "Action saved and will sync when connection returns.",
    ),
    pendingSync: text("إجراءات بانتظار المزامنة", "Actions waiting to sync"),
    syncedNow: text("تمت المزامنة بنجاح.", "Sync completed successfully."),
  },
  login: {
    title: text("دخول الطيار", "Hero sign in"),
    subtitle: text(
      "ادخل برقمك لعرض المهام والحالة والمستحقات.",
      "Sign in to access missions, status, and earnings.",
    ),
    gateway: text("بوابة العمل", "Operations access"),
    startWithPhone: text("ابدأ برقم الموبايل", "Start with phone number"),
    enterOtp: text("أدخل رمز التحقق", "Enter verification code"),
    phoneBody: text("أدخل رقم الموبايل المسجل للطيار.", "Enter the hero mobile number."),
    otpBody: text("أدخل رمز التحقق المرسل لك لإكمال الدخول.", "Enter the code sent to you to complete sign in."),
    phoneLabel: text("رقم الموبايل", "Mobile number"),
    otpLabel: text("رمز التحقق", "Verification code"),
    editPhone: text("تعديل الرقم", "Change number"),
    sendCode: text("إرسال الرمز", "Send code"),
    openBoard: text("فتح لوحة العمل", "Open work board"),
  },
  dashboard: {
    title: text("لوحة العمل", "Work board"),
    subtitle: text("مهامك الحالية، حالتك، ومستحقاتك في مكان واحد.", "Your active missions, status, and earnings in one place."),
    workState: text("حالة العمل", "Work status"),
    readyQuestion: text("جاهز لبدء العمل؟", "Ready to start receiving missions?"),
    onlineNow: text("أنت متصل حالياً", "You are online now"),
    offlineBody: text("فعّل الجاهزية لتصلك الطلبات الجديدة.", "Go online to receive new missions."),
    onlineBody: text("حالتك وموقعك يظهران للمشرف أثناء العمل.", "Your live status and location are visible to supervisors."),
    turnOn: text("تشغيل الجاهزية", "Go online"),
    turnOff: text("إيقاف الجاهزية", "Go offline"),
    activeMissions: text("المهام الحالية", "Active missions"),
    completedToday: text("الطلبات المكتملة", "Completed today"),
    todayIncome: text("دخل اليوم", "Today's earnings"),
    totalEarnings: text("إجمالي الأرباح", "Total earnings"),
    payoutDue: text("مستحقات قيد الصرف", "Pending payout"),
    quickView: text("ملخص سريع", "Quick summary"),
    todayMetrics: text("مؤشرات اليوم", "Today's metrics"),
    missionFlow: text("المهام", "Missions"),
    currentMissions: text("المهام الجارية", "Current missions"),
    missionsSubtitle: text("كل مهمة بحالتها الحالية والخطوة المطلوبة منك.", "Each mission with its current status and next step."),
    openMission: text("فتح المهمة", "Open mission"),
    lastSync: text("آخر مزامنة", "Last sync"),
    locationPermissionBody: text("فعّل إذن الموقع قبل تشغيل الجاهزية.", "Enable location permission before going online."),
    statusUpdated: text("تم تحديث الحالة.", "Status updated."),
    noMissionsOffline: text("فعّل الجاهزية لتظهر المهام هنا.", "Go online to see missions here."),
    noMissionsOnline: text("لا توجد مهام نشطة الآن.", "There are no active missions right now."),
    pendingSyncBody: text(
      "بعض الإجراءات محفوظة وسترسل تلقائياً عند عودة الاتصال.",
      "Some actions are saved and will sync automatically when connection returns.",
    ),
  },
  wallet: {
    title: text("المحفظة", "Wallet"),
    subtitle: text("رصيدك، الحركات المالية، وطلبات السحب.", "Your balance, transactions, and payout requests."),
    availableBalance: text("الرصيد المتاح", "Available balance"),
    withdrawNote: text("طلبات السحب تراجع من الإدارة المالية قبل التنفيذ.", "Payout requests are reviewed by finance before processing."),
    fullCashout: text("طلب سحب كامل الرصيد", "Withdraw full balance"),
    totalIncome: text("إجمالي المقبوض", "Total received"),
    totalDeductions: text("إجمالي الخصومات", "Total deductions"),
    ledger: text("السجل المالي", "Ledger"),
    latestMoves: text("آخر الحركات", "Latest transactions"),
    latestMovesSubtitle: text("كل حركة مالية مرتبطة بمحفظتك تظهر هنا.", "Every wallet transaction appears here."),
    filterAll: text("الكل", "All"),
    filterIn: text("إيداعات", "Money in"),
    filterOut: text("خصومات", "Money out"),
    filterPayout: text("سحب", "Payouts"),
    emptyTitle: text("لا توجد حركات بعد", "No transactions yet"),
    emptyBody: text("ستظهر الحركات هنا تلقائياً بمجرد تسجيلها.", "Transactions will appear here automatically."),
    filteredEmptyTitle: text("لا توجد نتائج لهذا الفلتر", "No transactions for this filter"),
    filteredEmptyBody: text("غيّر الفلتر أو حدّث الصفحة لعرض حركات أخرى.", "Change the filter or refresh to see other transactions."),
    noBalanceTitle: text("لا يوجد رصيد متاح", "No balance available"),
    noBalanceBody: text("الرصيد الحالي صفر، لذلك لا يمكن إنشاء طلب سحب الآن.", "Your current balance is zero, so a payout request cannot be created now."),
    createdTitle: text("تم إرسال الطلب", "Request sent"),
    createdBody: text("تم إرسال طلب السحب للمراجعة المالية.", "The payout request was sent for finance review."),
    completed: text("مكتمل", "Completed"),
    recorded: text("مسجل", "Recorded"),
  },
  order: {
    unavailable: text("هذه المهمة غير متاحة حالياً أو انتهت بالفعل.", "This mission is not available right now or has already ended."),
    loading: text("جارٍ تحميل تفاصيل المهمة...", "Loading mission details..."),
    currentMission: text("المهمة الحالية", "Current mission"),
    pickupFirst: text("اتجه إلى نقطة الاستلام أولاً.", "Head to the pickup point first."),
    enroute: text("أنت الآن في الطريق إلى العميل.", "You are now on the way to the customer."),
    handoff: text("راجع رمز التسليم قبل إنهاء المهمة.", "Verify the delivery code before closing the mission."),
    completed: text("تم إنهاء المهمة بنجاح.", "Mission completed successfully."),
    route: text("المسار", "Route"),
    routeTitle: text("تفاصيل المسار", "Route details"),
    routeSubtitle: text("الاستلام، التسليم، والتواصل السريع.", "Pickup, drop-off, and quick contact."),
    pickup: text("الاستلام", "Pickup"),
    dropoff: text("التسليم", "Drop-off"),
    branch: text("الفرع", "Branch"),
    unavailableAddress: text("العنوان غير متاح.", "Address unavailable."),
    callBranch: text("اتصال بالفرع", "Call branch"),
    callCustomer: text("اتصال بالعميل", "Call customer"),
    openMaps: text("فتح الملاحة", "Open navigation"),
    otpTitle: text("أدخل رمز التسليم", "Enter delivery code"),
    otpBody: text("اطلب من العميل رمز التسليم ثم أدخله هنا.", "Ask the customer for the delivery code and enter it here."),
    confirmPickup: text("تأكيد الاستلام", "Confirm pickup"),
    arrivedCustomer: text("وصلت إلى العميل", "Mark as arrived"),
    confirmDelivery: text("تأكيد التسليم", "Confirm delivery"),
    pickupStage: text("استلام", "Pickup"),
    enrouteStage: text("في الطريق", "En route"),
    handoffStage: text("تسليم", "Handoff"),
    doneStage: text("تمت", "Done"),
    reviewStage: text("مراجعة", "Review"),
    otpRequired: text("أدخل رمز تسليم مكوّن من 4 أرقام.", "Enter a 4-digit delivery code."),
    noPhoneTitle: text("الرقم غير متاح", "Phone unavailable"),
    noPhoneBody: text("لا يوجد رقم مسجل حالياً لهذا الطرف.", "No phone number is currently recorded."),
    callError: text("تعذر فتح تطبيق الاتصال.", "Could not open the phone app."),
    mapsError: text("تعذر فتح تطبيق الملاحة.", "Could not open the navigation app."),
    offlineQueuedBody: text("تم حفظ الخطوة وستتم مزامنتها عند عودة الاتصال.", "This step was saved and will sync when the connection returns."),
    verifyNeedsConnection: text("تأكيد التسليم يحتاج اتصالاً مباشراً بالإنترنت.", "Delivery confirmation requires a live internet connection."),
  },
} as const;
