import type { AppLocale, LocalizedText } from "./locale-context";

export const text = (ar: string, en: string): LocalizedText => ({ ar, en });

export function copyFor(locale: AppLocale, value: LocalizedText) {
  return locale === "ar" ? value.ar : value.en;
}

export const commonCopy = {
  dashboard: text("لوحة التحكم", "Dashboard"),
  details: text("التفاصيل", "Details"),
  save: text("حفظ", "Save"),
  close: text("إغلاق", "Close"),
  cancel: text("إلغاء", "Cancel"),
  search: text("بحث", "Search"),
  refresh: text("تحديث", "Refresh"),
  retry: text("إعادة المحاولة", "Retry"),
  loading: text("جارٍ التحميل", "Loading"),
  pending: text("قيد الانتظار", "Pending"),
  empty: text("لا توجد بيانات", "No data"),
  active: text("نشط", "Active"),
  inactive: text("موقوف", "Inactive"),
  connected: text("متصل", "Connected"),
  disconnected: text("غير متصل", "Offline"),
  reconnecting: text("إعادة اتصال", "Reconnecting"),
  noPhone: text("لا يوجد رقم", "No phone"),
  noEmail: text("لا يوجد بريد", "No email"),
  noAddress: text("لا يوجد عنوان", "No address"),
  noResults: text("لا توجد نتائج", "No results"),
  back: text("رجوع", "Back"),
  create: text("إضافة", "Create"),
  edit: text("تعديل", "Edit"),
  remove: text("حذف", "Remove"),
  yes: text("نعم", "Yes"),
  no: text("لا", "No"),
};

export const shellCopy = {
  brandName: text("طيّار", "Tayyar"),
  brandTagline: text("تشغيل واضح. تنفيذ أسرع.", "Clear ops. Faster execution."),
  roleDescription: {
    ADMIN: text("إدارة التشغيل والتنبيهات وحالة المنصة.", "Operations, alerts, and platform health."),
    SUPERVISOR: text("متابعة الطيارين والطلبات في الوقت الفعلي.", "Live crew and order follow-up."),
    MERCHANT_OWNER: text("طلباتك وعملاؤك وفروعك من شاشة واحدة.", "Orders, customers, and branches in one place."),
    BRANCH_MANAGER: text("متابعة طلبات الفرع وحالته التشغيلية.", "Branch orders and operating status."),
  } as const,
  openSidebar: text("فتح القائمة", "Open sidebar"),
  closeSidebar: text("إغلاق القائمة", "Close sidebar"),
  live: text("مباشر", "Live"),
  lightTheme: text("تشغيل السمة الفاتحة", "Use light theme"),
  darkTheme: text("تشغيل السمة الداكنة", "Use dark theme"),
  languageArabic: "العربية",
  languageEnglish: "English",
  navigation: text("التنقل", "Navigation"),
};

export const merchantOrderCopy = {
  bootLoading: text("جارٍ تجهيز بيانات المتجر", "Loading store data"),
  bootError: text("تعذر تحميل بيانات المتجر.", "Could not load store data."),
  startTitle: text("ابدأ برقم العميل", "Start with the customer phone"),
  startSubtitle: text("اكتب رقم العميل لعرض العناوين المحفوظة وآخر الطلبات.", "Enter the customer phone to load saved addresses and recent orders."),
  phonePlaceholder: text("رقم الموبايل", "Phone number"),
  continue: text("التالي", "Continue"),
  invalidPhone: text("اكتب رقم موبايل صحيح.", "Enter a valid phone number."),
  customerContext: text("بيانات العميل", "Customer context"),
  savedAddresses: text("العناوين المحفوظة", "Saved addresses"),
  noSavedAddress: text("لا يوجد عنوان محفوظ لهذا العميل.", "This customer has no saved address yet."),
  waitingCustomerLocation: text("في انتظار موقع العميل.", "Waiting for the customer location."),
  locationArrived: text("تم استلام موقع العميل.", "Customer location received."),
  locationRequestSent: text("تم إرسال طلب الموقع.", "Location request sent."),
  manualAddress: text("اكتب عنوان التوصيل", "Enter the delivery address"),
  geocodeAddress: text("راجع العنوان على الخريطة", "Review the address on the map"),
  geocodeCandidates: text("نتائج العنوان", "Address matches"),
  geocodeFallback: text("تعذر تحديد العنوان بدقة. اختر أقرب نتيجة أو اطلب الموقع من العميل.", "We could not pin the address precisely. Choose the closest match or ask the customer for location."),
  geocodeMissing: text("اكتب عنواناً واضحاً أولاً.", "Enter a clearer address first."),
  paymentState: text("حالة الدفع", "Payment status"),
  collectOnDelivery: text("تحصيل عند التسليم", "Collect on delivery"),
  alreadyPaid: text("مدفوع", "Prepaid"),
  amountToCollect: text("مبلغ التحصيل", "Collection amount"),
  prepaidIncludesFee: text("يشمل رسوم التوصيل", "Includes delivery fee"),
  deliveryFee: text("رسوم التوصيل", "Delivery fee"),
  createOrder: text("تأكيد الطلب", "Place order"),
  back: text("رجوع", "Back"),
  reset: text("بدء طلب جديد", "Start another order"),
  orderCreated: text("تم إنشاء الطلب.", "Order created."),
  openOrder: text("فتح الطلب", "Open order"),
  openTracking: text("فتح التتبع", "Open tracking"),
  connectionRetrying: text("التحديث المباشر يحاول العودة. يمكنك المتابعة الآن.", "Live updates are reconnecting. You can continue."),
  connectionOffline: text("التحديث المباشر غير متاح حالياً. يمكنك المتابعة وتحديث الصفحة عند الحاجة.", "Live updates are offline right now. You can continue and refresh if needed."),
  repeatCustomer: text("عميل متكرر", "Repeat customer"),
  lastAddress: text("آخر عنوان", "Last address"),
  lastOrder: text("آخر طلب", "Last order"),
  noAddressYet: text("لا يوجد عنوان بعد", "No address yet"),
  recentOrders: text("آخر الطلبات", "Recent orders"),
  noVisibleAddress: text("لا يوجد عنوان ظاهر", "No visible address"),
  askCustomerForLocation: text("اطلب الموقع من العميل", "Ask the customer for location"),
  askCustomerForLocationBody: text("إذا كان إرسال الموقع أسهل للعميل، أرسل الطلب من هنا.", "If sending a pin is easier, send the request from here."),
  sendLocationRequest: text("إرسال طلب موقع", "Send location request"),
  refresh: text("تحديث", "Refresh"),
  confirmAddressAndPayment: text("راجع العنوان والدفع", "Review address and payment"),
  deliveryAddress: text("عنوان التوصيل", "Delivery address"),
  noSecondaryLabel: text("لا يوجد وصف إضافي", "No extra label"),
  confirmedAddress: text("العنوان المعتمد", "Confirmed address"),
  chooseSavedOrReview: text("اختر عنواناً محفوظاً أو راجع العنوان على الخريطة قبل تأكيد الطلب.", "Choose a saved address or review the typed address before placing the order."),
  requestState: {
    PENDING: text("في انتظار العميل", "Waiting for customer"),
    RESOLVED: text("تم استلام الموقع", "Location received"),
    EXPIRED: text("انتهت صلاحية الطلب", "Request expired"),
    FAILED: text("فشل طلب الموقع", "Location request failed"),
  },
};

export const heroCopy = {
  dashboardTitle: text("لوحة العمل", "Work board"),
  dashboardSubtitle: text("المهام والحالة والمستحقات.", "Tasks, status, and earnings."),
  signOut: text("خروج", "Sign out"),
  loadError: text("تعذر تحميل البيانات.", "Could not load data."),
  refreshError: text("تعذر تحديث البيانات.", "Could not refresh data."),
  statusError: text("تعذر تحديث الحالة.", "Could not update status."),
  operatingState: text("حالة العمل", "Work status"),
  readyQuestion: text("جاهز للعمل؟", "Ready to go online?"),
  onlineNow: text("أنت متصل حالياً.", "You are online now."),
  offlineBody: text("فعّل الجاهزية لاستقبال المهام ومشاركة موقعك مع المشرف.", "Go online to receive tasks and share your live location."),
  onlineBody: text("حالتك وموقعك ظاهرين للمشرفين، وأي مهمة جديدة ستظهر هنا.", "Your status and location are visible to supervisors, and new tasks will appear here."),
  turnOn: text("تشغيل الجاهزية", "Go online"),
  turnOff: text("إيقاف الجاهزية", "Go offline"),
  activeMissions: text("المهام الحالية", "Active missions"),
  completedToday: text("طلبات مكتملة", "Completed today"),
  todayIncome: text("دخل اليوم", "Today's earnings"),
  totalEarnings: text("إجمالي الدخل", "Total earnings"),
  payoutDue: text("مستحقات السحب", "Pending payout"),
  quickView: text("ملخص سريع", "Quick summary"),
  missionFlow: text("المهام", "Missions"),
  noMissionsOffline: text("فعّل الجاهزية لتظهر المهام هنا.", "Go online to receive missions here."),
  noMissionsOnline: text("لا توجد مهام حالياً.", "No active missions right now."),
  openMission: text("فتح المهمة", "Open mission"),
};
